### ISSUE TITLE
Chainlink hackaton - midway check-in

### ISSUE THREAD

**Issue by korzewski** [korzewski/jackblock#14]
We need to sign into midway check-in of Chainlink Hackaton
This is required to get a main prize == t-shirt!

### Requirements
- Find out all the requirements, and make sure we're qualified for Chainlink Hackaton

### Additional resources
- https://chain.link/hackathon
- https://chainlink-2021.devpost.com/

**Comment by deployAt** [comment]
Midway check-in due: MARCH 30
