### ISSUE TITLE
Setup canonical address for dapp

### ISSUE THREAD

**Issue by tk-o** [korzewski/jackblock#54]
Some visitors might get 404 if we won't have a canonical address for our DAPP.

Make sure that requests to following addresses:
- `http://jackblock.network`
- `http://www.jackblock.network`
- `https://jackblock.network`
get permanently redirected (301) to the canonical location
`https://www.jackblock.network`

**Comment by korzewski** [comment]
I would suggest to redirect everything to https://jackblock.network (without www)

**Comment by tk-o** [comment]
https://betterprogramming.pub/traefik-2-1-as-a-reverse-proxy-c9e274da0a32 might be helpful while resolving
